### ISSUE TITLE
Bean command allows @everyone and @here pinging

### ISSUE THREAD

**Issue by MaxTechnics** [TeraBaito/jaidens-discord-utilities#13]
Example: a+bean @everyone

**Comment by TeraBaito** [comment]
![image](https://user-images.githubusercontent.com/59809717/123570298-28333980-d785-11eb-827f-9701e0519fa2.png)
lmao

**Comment by MaxTechnics** [comment]
You have to be kidding me smhsmhsmhsmhsmhsmh
