### ISSUE TITLE
I keep leaking my token (bruh)

### ISSUE THREAD

**Issue by TeraBaito** [TeraBaito/jaidens-discord-utilities#3]
yes

i just need to

- not commit -> push without checking well first
- if i do commit, check before pushing too
- revert commit and `git rm -rf --cached`, then unstage all changes
- not be stupid
p much lol

im actually glad Discord Police exists god bless

![me when token leaked](https://i.pinimg.com/originals/df/aa/c2/dfaac2eff98500483ba2c7ba5b7ea99d.png)

**Comment by MaxTechnics** [comment]
Kinemaster :jaidencringe:

**Comment by TeraBaito** [comment]
changed

**Comment by MaxTechnics** [comment]
gud
