### ISSUE TITLE
botConfig and botSettings aliases don't work

### ISSUE THREAD

**Issue by MaxTechnics** [TeraBaito/jaidens-discord-utilities#5]
Because the commandhandler takes the message.toLowerCase() it is literally impossible for it to react to any command or alias with uppercase characters.

So either do something with the handler, or just change them to lowercase aliases

**Comment by TeraBaito** [comment]
Yeah, I think this is more of a problem onto how I implement my code rather than how the user does it kekw; either way I'm going to fix the command handler so it can accept camelCase and such (this would also make me wanna do a name refactor to use alias so it looks cooler with camelCase)
