### ISSUE TITLE
AFK removes the first 6 chars of your nickname instead of '[AFK]'

### ISSUE THREAD

**Issue by MaxTechnics** [TeraBaito/jaidens-discord-utilities#9]
So if you're an idiot, like meself. And you update your nickname, you will wake up to 's Physics Homework'. Making the bot look for the afk string is probably  a better way. Will have a look

**Comment by TeraBaito** [comment]
oh, so I also forgot to make it not do the auto nickname removal when a person's nickname (+ 'AFK') is 32 chars

**Comment by TeraBaito** [comment]
nevermind, I get what you mean now. I'll make it check if the display name starts with 'AFK' at the time of the removal. Quick tip, if you don't want it to auto-change your nickname use the `-n` flag
